Find all detailed documentation of the code in the following link:
http://www.researchgate.net/publication/280610256_Development_and_Implementation_of_GPS_Correlator_Structures_in_MATLAB_and_Simulink_with_Focus_on_SDR_Applications
